name: push-to-server
run-name: Now pushing to server
concurrency: production
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs: 
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps: 
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/pk
          chmod 600 ~/.ssh/pk
          cat >>~/.ssh/config <<END
          Host server
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/pk
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SERVER_SSH_USER }}
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SSH_HOST: ${{ secrets.SERVER_SSH_HOST }}
      - name: Pull Git
        run: ssh server 'cd public_html && git pull'
  
